// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request for
/// [DeleteQueuedResource][google.cloud.tpu.v2.Tpu.DeleteQueuedResource].
///
/// [google.cloud.tpu.v2.Tpu.DeleteQueuedResource]: <doc:TpuClient/deleteQueuedResource(request:options:)>
public struct DeleteQueuedResourceRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name.
  public var name: Swift.String = Swift.String()

  /// Optional. Idempotent request UUID.
  public var requestId: Swift.String = Swift.String()

  /// Optional. If set to true, all running nodes belonging to this queued
  /// resource will be deleted first and then the queued resource will be
  /// deleted. Otherwise (i.e. force=false), the queued resource will only be
  /// deleted if its nodes have already been deleted or the queued resource is in
  /// the ACCEPTED, FAILED, or SUSPENDED state.
  public var force: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DeleteQueuedResourceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeleteQueuedResourceRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let requestId = CodingKeys(stringValue: "requestId")
    static let force = CodingKeys(stringValue: "force")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "requestId",
      "force",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .requestId) {
      self.requestId = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .force) {
      self.force = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.requestId, forKey: .requestId)
    try container.encode(self.force, forKey: .force)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `DeleteQueuedResourceRequest`: `"type.googleapis.com/google.cloud.tpu.v2.DeleteQueuedResourceRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tpu.v2.DeleteQueuedResourceRequest"
  }

  /// Initialize an instance of `DeleteQueuedResourceRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.tpu.v2.DeleteQueuedResourceRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `DeleteQueuedResourceRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
