// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Network related configurations.
public struct NetworkConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The name of the network for the TPU node. It must be a preexisting Google
  /// Compute Engine network. If none is provided, "default" will be used.
  public var network: Swift.String = Swift.String()

  /// The name of the subnetwork for the TPU node. It must be a preexisting
  /// Google Compute Engine subnetwork. If none is provided, "default" will be
  /// used.
  public var subnetwork: Swift.String = Swift.String()

  /// Indicates that external IP addresses would be associated with the TPU
  /// workers. If set to false, the specified subnetwork or network should have
  /// Private Google Access enabled.
  public var enableExternalIps: Swift.Bool = Swift.Bool()

  /// Allows the TPU node to send and receive packets with non-matching
  /// destination or source IPs. This is required if you plan to use the TPU
  /// workers to forward routes.
  public var canIpForward: Swift.Bool = Swift.Bool()

  /// Optional. Specifies networking queue count for TPU VM instance's network
  /// interface.
  public var queueCount: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `NetworkConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NetworkConfig().with { $0.network = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let network = CodingKeys(stringValue: "network")
    static let subnetwork = CodingKeys(stringValue: "subnetwork")
    static let enableExternalIps = CodingKeys(stringValue: "enableExternalIps")
    static let canIpForward = CodingKeys(stringValue: "canIpForward")
    static let queueCount = CodingKeys(stringValue: "queueCount")

    static let _knownKeys: Set<Swift.String> = [
      "network",
      "subnetwork",
      "enableExternalIps",
      "canIpForward",
      "queueCount",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
      self.network = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subnetwork) {
      self.subnetwork = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableExternalIps) {
      self.enableExternalIps = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .canIpForward) {
      self.canIpForward = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .queueCount) {
      self.queueCount = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.network, forKey: .network)
    try container.encode(self.subnetwork, forKey: .subnetwork)
    try container.encode(self.enableExternalIps, forKey: .enableExternalIps)
    try container.encode(self.canIpForward, forKey: .canIpForward)
    try container.encode(self.queueCount, forKey: .queueCount)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `NetworkConfig`: `"type.googleapis.com/google.cloud.tpu.v2.NetworkConfig"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tpu.v2.NetworkConfig"
  }

  /// Initialize an instance of `NetworkConfig` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.tpu.v2.NetworkConfig"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `NetworkConfig` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
