// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Metadata describing an [Operation][google.longrunning.Operation]
///
/// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
public struct OperationMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The time the operation was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// The time the operation finished running.
  public var endTime: GoogleWKT.WKTTimestamp? = nil

  /// Target of the operation - for example
  /// projects/project-1/connectivityTests/test-1
  public var target: Swift.String = Swift.String()

  /// Name of the verb executed by the operation.
  public var verb: Swift.String = Swift.String()

  /// Human-readable status of the operation, if any.
  public var statusDetail: Swift.String = Swift.String()

  /// Specifies if cancellation was requested for the operation.
  public var cancelRequested: Swift.Bool = Swift.Bool()

  /// API version.
  public var apiVersion: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OperationMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OperationMetadata().with { $0.createTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let createTime = CodingKeys(stringValue: "createTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let target = CodingKeys(stringValue: "target")
    static let verb = CodingKeys(stringValue: "verb")
    static let statusDetail = CodingKeys(stringValue: "statusDetail")
    static let cancelRequested = CodingKeys(stringValue: "cancelRequested")
    static let apiVersion = CodingKeys(stringValue: "apiVersion")

    static let _knownKeys: Set<Swift.String> = [
      "createTime",
      "endTime",
      "target",
      "verb",
      "statusDetail",
      "cancelRequested",
      "apiVersion",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .endTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .target) {
      self.target = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .verb) {
      self.verb = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .statusDetail) {
      self.statusDetail = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .cancelRequested) {
      self.cancelRequested = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .apiVersion) {
      self.apiVersion = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encode(self.target, forKey: .target)
    try container.encode(self.verb, forKey: .verb)
    try container.encode(self.statusDetail, forKey: .statusDetail)
    try container.encode(self.cancelRequested, forKey: .cancelRequested)
    try container.encode(self.apiVersion, forKey: .apiVersion)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tpu.v2.OperationMetadata"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
