// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleType
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A QueuedResource represents a request for resources that will be placed
/// in a queue and fulfilled when the necessary resources are available.
public struct QueuedResource: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Immutable. The name of the QueuedResource.
  public var name: Swift.String = Swift.String()

  /// Output only. The time when the QueuedResource was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. The queueing policy of the QueuedRequest.
  public var queueingPolicy: QueuedResource.QueueingPolicy? = nil

  /// Output only. State of the QueuedResource request.
  public var state: QueuedResourceState? = nil

  /// Optional. Name of the reservation in which the resource should be
  /// provisioned. Format:
  /// projects/{project}/locations/{zone}/reservations/{reservation}
  public var reservationName: Swift.String = Swift.String()

  /// Resource specification.
  public var resource: ResourceOneOf? = nil

  /// Tier specifies the required tier.
  public var tier: TierOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `QueuedResource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QueuedResource().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let tpu = CodingKeys(stringValue: "tpu")
    static let spot = CodingKeys(stringValue: "spot")
    static let guaranteed = CodingKeys(stringValue: "guaranteed")
    static let queueingPolicy = CodingKeys(stringValue: "queueingPolicy")
    static let state = CodingKeys(stringValue: "state")
    static let reservationName = CodingKeys(stringValue: "reservationName")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "tpu",
      "spot",
      "guaranteed",
      "queueingPolicy",
      "state",
      "reservationName",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.queueingPolicy = try container.decodeIfPresent(
      QueuedResource.QueueingPolicy.self, forKey: .queueingPolicy)
    self.state = try container.decodeIfPresent(QueuedResourceState.self, forKey: .state)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .reservationName) {
      self.reservationName = value
    }

    var resource: ResourceOneOf? = nil
    let resourceCheckAndSet = {
      if resource != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'resource'"))
      }
      resource = $0
    }
    if let tpu = try container.decodeIfPresent(QueuedResource.Tpu.self, forKey: .tpu) {
      try resourceCheckAndSet(.tpu(tpu))
    }
    self.resource = resource

    var tier: TierOneOf? = nil
    let tierCheckAndSet = {
      if tier != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'tier'"
          ))
      }
      tier = $0
    }
    if let spot = try container.decodeIfPresent(QueuedResource.Spot.self, forKey: .spot) {
      try tierCheckAndSet(.spot(spot))
    }
    if let guaranteed = try container.decodeIfPresent(
      QueuedResource.Guaranteed.self, forKey: .guaranteed)
    {
      try tierCheckAndSet(.guaranteed(guaranteed))
    }
    self.tier = tier
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.queueingPolicy, forKey: .queueingPolicy)
    try container.encodeIfPresent(self.state, forKey: .state)
    try container.encode(self.reservationName, forKey: .reservationName)

    if let choice = self.resource {
      switch choice {
      case .tpu(let value):
        try container.encode(value, forKey: .tpu)
      }
    }

    if let choice = self.tier {
      switch choice {
      case .spot(let value):
        try container.encode(value, forKey: .spot)
      case .guaranteed(let value):
        try container.encode(value, forKey: .guaranteed)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Details of the TPU resource(s) being requested.
  public struct Tpu: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The TPU node(s) being requested.
    public var nodeSpec: [QueuedResource.Tpu.NodeSpec] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Tpu`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Tpu().with { $0.nodeSpec = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let nodeSpec = CodingKeys(stringValue: "nodeSpec")

      static let _knownKeys: Set<Swift.String> = [
        "nodeSpec"
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [QueuedResource.Tpu.NodeSpec].self, forKey: .nodeSpec)
      {
        self.nodeSpec = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.nodeSpec, forKey: .nodeSpec)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Details of the TPU node(s) being requested. Users can request either a
    /// single node or multiple nodes.
    /// NodeSpec provides the specification for node(s) to be created.
    public struct NodeSpec: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Required. The parent resource name.
      public var parent: Swift.String = Swift.String()

      /// Required. The node.
      public var node: Node? = nil

      /// Either a node_id or multislice_params.
      public var nameStrategy: NameStrategyOneOf? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `NodeSpec`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = NodeSpec().with { $0.parent = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let parent = CodingKeys(stringValue: "parent")
        static let nodeId = CodingKeys(stringValue: "nodeId")
        static let multisliceParams = CodingKeys(stringValue: "multisliceParams")
        static let node = CodingKeys(stringValue: "node")

        static let _knownKeys: Set<Swift.String> = [
          "parent",
          "nodeId",
          "multisliceParams",
          "node",
        ]
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
          self.parent = value
        }
        self.node = try container.decodeIfPresent(Node.self, forKey: .node)

        var nameStrategy: NameStrategyOneOf? = nil
        let nameStrategyCheckAndSet = {
          if nameStrategy != nil {
            throw DecodingError.dataCorrupted(
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Multiple values set for oneof 'nameStrategy'"))
          }
          nameStrategy = $0
        }
        if let nodeId = try container.decodeIfPresent(Swift.String.self, forKey: .nodeId) {
          try nameStrategyCheckAndSet(.nodeId(nodeId))
        }
        if let multisliceParams = try container.decodeIfPresent(
          QueuedResource.Tpu.NodeSpec.MultisliceParams.self, forKey: .multisliceParams)
        {
          try nameStrategyCheckAndSet(.multisliceParams(multisliceParams))
        }
        self.nameStrategy = nameStrategy
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.parent, forKey: .parent)
        try container.encodeIfPresent(self.node, forKey: .node)

        if let choice = self.nameStrategy {
          switch choice {
          case .nodeId(let value):
            try container.encode(value, forKey: .nodeId)
          case .multisliceParams(let value):
            try container.encode(value, forKey: .multisliceParams)
          }
        }
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// Parameters to specify for multislice QueuedResource requests. This
      /// message must be populated in case of multislice requests instead of
      /// node_id.
      public struct MultisliceParams: Codable, Equatable, GoogleWKT._AnyPackable,
        Sendable
      {
        /// Required. Number of nodes with this spec. The system will attempt
        /// to provision "node_count" nodes as part of the request.
        /// This needs to be > 1.
        public var nodeCount: Swift.Int32 = Swift.Int32()

        /// Optional. Prefix of node_ids in case of multislice request.
        /// Should follow the `^[A-Za-z0-9_.~+%-]+$` regex format.
        /// If node_count = 3 and node_id_prefix = "np", node ids of nodes
        /// created will be "np-0", "np-1", "np-2". If this field is not
        /// provided we use queued_resource_id as the node_id_prefix.
        public var nodeIdPrefix: Swift.String = Swift.String()

        @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

        /// Initialize a new instance of `MultisliceParams`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = MultisliceParams().with { $0.nodeCount = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        private struct CodingKeys: CodingKey {
          var stringValue: Swift.String
          var intValue: Swift.Int? { nil }
          init(stringValue: Swift.String) { self.stringValue = stringValue }
          init?(intValue: Swift.Int) { nil }

          static let nodeCount = CodingKeys(stringValue: "nodeCount")
          static let nodeIdPrefix = CodingKeys(stringValue: "nodeIdPrefix")

          static let _knownKeys: Set<Swift.String> = [
            "nodeCount",
            "nodeIdPrefix",
          ]
        }

        public init(from decoder: any Decoder) throws {
          let container = try decoder.container(keyedBy: CodingKeys.self)
          if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .nodeCount) {
            self.nodeCount = value
          }
          if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nodeIdPrefix) {
            self.nodeIdPrefix = value
          }
          for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
            self._unknownFields.json[key.stringValue] = try container.decode(
              GoogleWKT.WKTValue.self, forKey: key)
          }
        }

        public func encode(to encoder: any Encoder) throws {
          var container = encoder.container(keyedBy: CodingKeys.self)
          try container.encode(self.nodeCount, forKey: .nodeCount)
          try container.encode(self.nodeIdPrefix, forKey: .nodeIdPrefix)
          for (key, value) in self._unknownFields.json {
            try container.encode(value, forKey: CodingKeys(stringValue: key))
          }
        }

        /// The type URL for `MultisliceParams`: `"type.googleapis.com/google.cloud.tpu.v2.QueuedResource.Tpu.NodeSpec.MultisliceParams"`.
        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.tpu.v2.QueuedResource.Tpu.NodeSpec.MultisliceParams"
        }

        /// Initialize an instance of `MultisliceParams` by unpacking from a `GoogleWKT.WKTAny`.
        ///
        /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
        /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.tpu.v2.QueuedResource.Tpu.NodeSpec.MultisliceParams"`,
        ///   or if deserialization fails.
        public init(fromAny any: GoogleWKT.WKTAny) throws {
          self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
        }

        /// Packs this `MultisliceParams` into a `GoogleWKT.WKTStruct` representation.
        ///
        /// - Throws: An error if serialization fails.
        public func _pack() throws -> GoogleWKT.WKTStruct {
          return try GoogleWKT._slowAnySerialize(message: self)
        }
      }

      /// Either a node_id or multislice_params.
      public enum NameStrategyOneOf: Codable, Equatable, Sendable {
        /// Optional. The unqualified resource name. Should follow the
        /// `^[A-Za-z0-9_.~+%-]+$` regex format. This is only specified when
        /// requesting a single node. In case of multislice requests,
        /// multislice_params must be populated instead.
        case nodeId(Swift.String)
        /// Optional. Fields to specify in case of multislice request.
        indirect case multisliceParams(QueuedResource.Tpu.NodeSpec.MultisliceParams)
      }

      /// The type URL for `NodeSpec`: `"type.googleapis.com/google.cloud.tpu.v2.QueuedResource.Tpu.NodeSpec"`.
      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.tpu.v2.QueuedResource.Tpu.NodeSpec"
      }

      /// Initialize an instance of `NodeSpec` by unpacking from a `GoogleWKT.WKTAny`.
      ///
      /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
      /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.tpu.v2.QueuedResource.Tpu.NodeSpec"`,
      ///   or if deserialization fails.
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }

      /// Packs this `NodeSpec` into a `GoogleWKT.WKTStruct` representation.
      ///
      /// - Throws: An error if serialization fails.
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// The type URL for `Tpu`: `"type.googleapis.com/google.cloud.tpu.v2.QueuedResource.Tpu"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.tpu.v2.QueuedResource.Tpu"
    }

    /// Initialize an instance of `Tpu` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.tpu.v2.QueuedResource.Tpu"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `Tpu` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Spot tier definition.
  public struct Spot: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Spot`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Spot().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let _knownKeys: Set<Swift.String> = []
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `Spot`: `"type.googleapis.com/google.cloud.tpu.v2.QueuedResource.Spot"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.tpu.v2.QueuedResource.Spot"
    }

    /// Initialize an instance of `Spot` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.tpu.v2.QueuedResource.Spot"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `Spot` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Guaranteed tier definition.
  public struct Guaranteed: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Defines the minimum duration of the guarantee. If specified,
    /// the requested resources will only be provisioned if they can be
    /// allocated for at least the given duration.
    public var minDuration: GoogleWKT.WKTDuration? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Guaranteed`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Guaranteed().with { $0.minDuration = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let minDuration = CodingKeys(stringValue: "minDuration")

      static let _knownKeys: Set<Swift.String> = [
        "minDuration"
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.minDuration = try container.decodeIfPresent(
        GoogleWKT.WKTDuration.self, forKey: .minDuration)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.minDuration, forKey: .minDuration)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `Guaranteed`: `"type.googleapis.com/google.cloud.tpu.v2.QueuedResource.Guaranteed"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.tpu.v2.QueuedResource.Guaranteed"
    }

    /// Initialize an instance of `Guaranteed` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.tpu.v2.QueuedResource.Guaranteed"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `Guaranteed` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Defines the policy of the QueuedRequest.
  public struct QueueingPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Time flexibility specification.
    public var startTimingConstraints: StartTimingConstraintsOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `QueueingPolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = QueueingPolicy().with { $0.validUntilDuration = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let validUntilDuration = CodingKeys(stringValue: "validUntilDuration")
      static let validUntilTime = CodingKeys(stringValue: "validUntilTime")
      static let validAfterDuration = CodingKeys(stringValue: "validAfterDuration")
      static let validAfterTime = CodingKeys(stringValue: "validAfterTime")
      static let validInterval = CodingKeys(stringValue: "validInterval")

      static let _knownKeys: Set<Swift.String> = [
        "validUntilDuration",
        "validUntilTime",
        "validAfterDuration",
        "validAfterTime",
        "validInterval",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var startTimingConstraints: StartTimingConstraintsOneOf? = nil
      let startTimingConstraintsCheckAndSet = {
        if startTimingConstraints != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'startTimingConstraints'"))
        }
        startTimingConstraints = $0
      }
      if let validUntilDuration = try container.decodeIfPresent(
        GoogleWKT.WKTDuration.self, forKey: .validUntilDuration)
      {
        try startTimingConstraintsCheckAndSet(.validUntilDuration(validUntilDuration))
      }
      if let validUntilTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .validUntilTime)
      {
        try startTimingConstraintsCheckAndSet(.validUntilTime(validUntilTime))
      }
      if let validAfterDuration = try container.decodeIfPresent(
        GoogleWKT.WKTDuration.self, forKey: .validAfterDuration)
      {
        try startTimingConstraintsCheckAndSet(.validAfterDuration(validAfterDuration))
      }
      if let validAfterTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .validAfterTime)
      {
        try startTimingConstraintsCheckAndSet(.validAfterTime(validAfterTime))
      }
      if let validInterval = try container.decodeIfPresent(
        GoogleType.Interval.self, forKey: .validInterval)
      {
        try startTimingConstraintsCheckAndSet(.validInterval(validInterval))
      }
      self.startTimingConstraints = startTimingConstraints
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.startTimingConstraints {
        switch choice {
        case .validUntilDuration(let value):
          try container.encode(value, forKey: .validUntilDuration)
        case .validUntilTime(let value):
          try container.encode(value, forKey: .validUntilTime)
        case .validAfterDuration(let value):
          try container.encode(value, forKey: .validAfterDuration)
        case .validAfterTime(let value):
          try container.encode(value, forKey: .validAfterTime)
        case .validInterval(let value):
          try container.encode(value, forKey: .validInterval)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Time flexibility specification.
    public enum StartTimingConstraintsOneOf: Codable, Equatable, Sendable {
      /// Optional. A relative time after which resources should not be created.
      /// If the request cannot be fulfilled by this time the request will be
      /// failed.
      indirect case validUntilDuration(GoogleWKT.WKTDuration)
      /// Optional. An absolute time after which resources should not be created.
      /// If the request cannot be fulfilled by this time the request will be
      /// failed.
      indirect case validUntilTime(GoogleWKT.WKTTimestamp)
      /// Optional. A relative time after which resources may be created.
      indirect case validAfterDuration(GoogleWKT.WKTDuration)
      /// Optional. An absolute time after which resources may be created.
      indirect case validAfterTime(GoogleWKT.WKTTimestamp)
      /// Optional. An absolute time interval within which resources may be
      /// created.
      indirect case validInterval(GoogleType.Interval)
    }

    /// The type URL for `QueueingPolicy`: `"type.googleapis.com/google.cloud.tpu.v2.QueuedResource.QueueingPolicy"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.tpu.v2.QueuedResource.QueueingPolicy"
    }

    /// Initialize an instance of `QueueingPolicy` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.tpu.v2.QueuedResource.QueueingPolicy"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `QueueingPolicy` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Resource specification.
  public enum ResourceOneOf: Codable, Equatable, Sendable {
    /// Optional. Defines a TPU resource.
    indirect case tpu(QueuedResource.Tpu)
  }

  /// Tier specifies the required tier.
  public enum TierOneOf: Codable, Equatable, Sendable {
    /// Optional. The Spot tier.
    indirect case spot(QueuedResource.Spot)
    /// Optional. The Guaranteed tier
    indirect case guaranteed(QueuedResource.Guaranteed)
  }

  /// The type URL for `QueuedResource`: `"type.googleapis.com/google.cloud.tpu.v2.QueuedResource"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tpu.v2.QueuedResource"
  }

  /// Initialize an instance of `QueuedResource` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.tpu.v2.QueuedResource"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `QueuedResource` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
