// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Sets the scheduling options for this node.
public struct SchedulingConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Defines whether the node is preemptible.
  public var preemptible: Swift.Bool = Swift.Bool()

  /// Whether the node is created under a reservation.
  public var reserved: Swift.Bool = Swift.Bool()

  /// Optional. Defines whether the node is Spot VM.
  public var spot: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SchedulingConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SchedulingConfig().with { $0.preemptible = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let preemptible = CodingKeys(stringValue: "preemptible")
    static let reserved = CodingKeys(stringValue: "reserved")
    static let spot = CodingKeys(stringValue: "spot")

    static let _knownKeys: Set<Swift.String> = [
      "preemptible",
      "reserved",
      "spot",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .preemptible) {
      self.preemptible = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .reserved) {
      self.reserved = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .spot) {
      self.spot = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.preemptible, forKey: .preemptible)
    try container.encode(self.reserved, forKey: .reserved)
    try container.encode(self.spot, forKey: .spot)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tpu.v2.SchedulingConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
