// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A Symptom instance.
public struct Symptom: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Timestamp when the Symptom is created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Type of the Symptom.
  public var symptomType: Symptom.SymptomType = Symptom.SymptomType()

  /// Detailed information of the current Symptom.
  public var details: Swift.String = Swift.String()

  /// A string used to uniquely distinguish a worker within a TPU node.
  public var workerId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Symptom`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Symptom().with { $0.createTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let createTime = CodingKeys(stringValue: "createTime")
    static let symptomType = CodingKeys(stringValue: "symptomType")
    static let details = CodingKeys(stringValue: "details")
    static let workerId = CodingKeys(stringValue: "workerId")

    static let _knownKeys: Set<Swift.String> = [
      "createTime",
      "symptomType",
      "details",
      "workerId",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    if let value = try container.decodeIfPresent(Symptom.SymptomType.self, forKey: .symptomType) {
      self.symptomType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .details) {
      self.details = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .workerId) {
      self.workerId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encode(self.symptomType, forKey: .symptomType)
    try container.encode(self.details, forKey: .details)
    try container.encode(self.workerId, forKey: .workerId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// SymptomType represents the different types of Symptoms that a TPU can be
  /// at.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum SymptomType: Codable, Equatable, Hashable, Sendable {
    /// Unspecified symptom.
    case unspecified
    /// TPU VM memory is low.
    case lowMemory
    /// TPU runtime is out of memory.
    case outOfMemory
    /// TPU runtime execution has timed out.
    case executeTimedOut
    /// TPU runtime fails to construct a mesh that recognizes each TPU device's
    /// neighbors.
    case meshBuildFail
    /// TPU HBM is out of memory.
    case hbmOutOfMemory
    /// Abusive behaviors have been identified on the current project.
    case projectAbuse
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .lowMemory: return 1
      case .outOfMemory: return 2
      case .executeTimedOut: return 3
      case .meshBuildFail: return 4
      case .hbmOutOfMemory: return 5
      case .projectAbuse: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SYMPTOM_TYPE_UNSPECIFIED"
      case .lowMemory: return "LOW_MEMORY"
      case .outOfMemory: return "OUT_OF_MEMORY"
      case .executeTimedOut: return "EXECUTE_TIMED_OUT"
      case .meshBuildFail: return "MESH_BUILD_FAIL"
      case .hbmOutOfMemory: return "HBM_OUT_OF_MEMORY"
      case .projectAbuse: return "PROJECT_ABUSE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SymptomType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SYMPTOM_TYPE_UNSPECIFIED": self = .unspecified
      case "LOW_MEMORY": self = .lowMemory
      case "OUT_OF_MEMORY": self = .outOfMemory
      case "EXECUTE_TIMED_OUT": self = .executeTimedOut
      case "MESH_BUILD_FAIL": self = .meshBuildFail
      case "HBM_OUT_OF_MEMORY": self = .hbmOutOfMemory
      case "PROJECT_ABUSE": self = .projectAbuse
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SymptomType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .lowMemory
      case 2: self = .outOfMemory
      case 3: self = .executeTimedOut
      case 4: self = .meshBuildFail
      case 5: self = .hbmOutOfMemory
      case 6: self = .projectAbuse
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SYMPTOM_TYPE_UNSPECIFIED")
      case .lowMemory: return try container.encode("LOW_MEMORY")
      case .outOfMemory: return try container.encode("OUT_OF_MEMORY")
      case .executeTimedOut: return try container.encode("EXECUTE_TIMED_OUT")
      case .meshBuildFail: return try container.encode("MESH_BUILD_FAIL")
      case .hbmOutOfMemory: return try container.encode("HBM_OUT_OF_MEMORY")
      case .projectAbuse: return try container.encode("PROJECT_ABUSE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `Symptom`: `"type.googleapis.com/google.cloud.tpu.v2.Symptom"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tpu.v2.Symptom"
  }

  /// Initialize an instance of `Symptom` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.tpu.v2.Symptom"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `Symptom` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
