// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Manages TPU nodes and other resources
///
/// TPU API v2
///
/// @Snippet(path: "TpuQuickstart")
public final class TpuClient: Clients.TpuProtocol, Sendable {
  let inner: any Clients.TpuStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.PollingBackoffPolicy

  /// Creates a new `TpuClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.TpuStub = try Clients.TpuTransport(options)
    inner = Clients.TpuRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.TpuLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists nodes.
  ///
  /// @Snippet(path: "Tpu_ListNodes")
  public func listNodes(
    request: ListNodesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTpuV2.ListNodesResponse {
    try await self.inner.listNodes(request: request, options: options)
  }

  /// Gets the details of a node.
  ///
  /// @Snippet(path: "Tpu_GetNode")
  public func getNode(
    request: GetNodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTpuV2.Node {
    try await self.inner.getNode(request: request, options: options)
  }

  /// Creates a node.
  ///
  /// @Snippet(path: "Tpu_CreateNode")
  public func createNode(
    request: CreateNodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createNode(request: request, options: options)
  }

  /// Creates a node.
  ///
  /// @Snippet(path: "Tpu_CreateNode")
  public func createNodePollingUntilDone(
    request: CreateNodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> Node {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Node>.State in
      return try op._extractStatus(Node.self)
    }
    let rawOp = try await self.createNode(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Node>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Deletes a node.
  ///
  /// @Snippet(path: "Tpu_DeleteNode")
  public func deleteNode(
    request: DeleteNodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteNode(request: request, options: options)
  }

  /// Deletes a node.
  ///
  /// @Snippet(path: "Tpu_DeleteNode")
  public func deleteNodePollingUntilDone(
    request: DeleteNodeRequest, options: GoogleGax.RequestOptions
  ) async throws {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteNode(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    try await poller.wait()
  }

  /// Stops a node. This operation is only available with single TPU nodes.
  ///
  /// @Snippet(path: "Tpu_StopNode")
  public func stopNode(
    request: StopNodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.stopNode(request: request, options: options)
  }

  /// Stops a node. This operation is only available with single TPU nodes.
  ///
  /// @Snippet(path: "Tpu_StopNode")
  public func stopNodePollingUntilDone(
    request: StopNodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> Node {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Node>.State in
      return try op._extractStatus(Node.self)
    }
    let rawOp = try await self.stopNode(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Node>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Starts a node.
  ///
  /// @Snippet(path: "Tpu_StartNode")
  public func startNode(
    request: StartNodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.startNode(request: request, options: options)
  }

  /// Starts a node.
  ///
  /// @Snippet(path: "Tpu_StartNode")
  public func startNodePollingUntilDone(
    request: StartNodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> Node {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Node>.State in
      return try op._extractStatus(Node.self)
    }
    let rawOp = try await self.startNode(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Node>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Updates the configurations of a node.
  ///
  /// @Snippet(path: "Tpu_UpdateNode")
  public func updateNode(
    request: UpdateNodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateNode(request: request, options: options)
  }

  /// Updates the configurations of a node.
  ///
  /// @Snippet(path: "Tpu_UpdateNode")
  public func updateNodePollingUntilDone(
    request: UpdateNodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> Node {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Node>.State in
      return try op._extractStatus(Node.self)
    }
    let rawOp = try await self.updateNode(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Node>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Lists queued resources.
  ///
  /// @Snippet(path: "Tpu_ListQueuedResources")
  public func listQueuedResources(
    request: ListQueuedResourcesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTpuV2.ListQueuedResourcesResponse {
    try await self.inner.listQueuedResources(request: request, options: options)
  }

  /// Gets details of a queued resource.
  ///
  /// @Snippet(path: "Tpu_GetQueuedResource")
  public func getQueuedResource(
    request: GetQueuedResourceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTpuV2.QueuedResource {
    try await self.inner.getQueuedResource(request: request, options: options)
  }

  /// Creates a QueuedResource TPU instance.
  ///
  /// @Snippet(path: "Tpu_CreateQueuedResource")
  public func createQueuedResource(
    request: CreateQueuedResourceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createQueuedResource(request: request, options: options)
  }

  /// Creates a QueuedResource TPU instance.
  ///
  /// @Snippet(path: "Tpu_CreateQueuedResource")
  public func createQueuedResourcePollingUntilDone(
    request: CreateQueuedResourceRequest, options: GoogleGax.RequestOptions
  ) async throws -> QueuedResource {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<QueuedResource>.State in
      return try op._extractStatus(QueuedResource.self)
    }
    let rawOp = try await self.createQueuedResource(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<QueuedResource>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Deletes a QueuedResource TPU instance.
  ///
  /// @Snippet(path: "Tpu_DeleteQueuedResource")
  public func deleteQueuedResource(
    request: DeleteQueuedResourceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteQueuedResource(request: request, options: options)
  }

  /// Deletes a QueuedResource TPU instance.
  ///
  /// @Snippet(path: "Tpu_DeleteQueuedResource")
  public func deleteQueuedResourcePollingUntilDone(
    request: DeleteQueuedResourceRequest, options: GoogleGax.RequestOptions
  ) async throws {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteQueuedResource(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    try await poller.wait()
  }

  /// Resets a QueuedResource TPU instance
  ///
  /// @Snippet(path: "Tpu_ResetQueuedResource")
  public func resetQueuedResource(
    request: ResetQueuedResourceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.resetQueuedResource(request: request, options: options)
  }

  /// Resets a QueuedResource TPU instance
  ///
  /// @Snippet(path: "Tpu_ResetQueuedResource")
  public func resetQueuedResourcePollingUntilDone(
    request: ResetQueuedResourceRequest, options: GoogleGax.RequestOptions
  ) async throws -> QueuedResource {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<QueuedResource>.State in
      return try op._extractStatus(QueuedResource.self)
    }
    let rawOp = try await self.resetQueuedResource(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<QueuedResource>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Generates the Cloud TPU service identity for the project.
  ///
  /// @Snippet(path: "Tpu_GenerateServiceIdentity")
  public func generateServiceIdentity(
    request: GenerateServiceIdentityRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTpuV2.GenerateServiceIdentityResponse {
    try await self.inner.generateServiceIdentity(request: request, options: options)
  }

  /// Lists accelerator types supported by this API.
  ///
  /// @Snippet(path: "Tpu_ListAcceleratorTypes")
  public func listAcceleratorTypes(
    request: ListAcceleratorTypesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTpuV2.ListAcceleratorTypesResponse {
    try await self.inner.listAcceleratorTypes(request: request, options: options)
  }

  /// Gets AcceleratorType.
  ///
  /// @Snippet(path: "Tpu_GetAcceleratorType")
  public func getAcceleratorType(
    request: GetAcceleratorTypeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTpuV2.AcceleratorType {
    try await self.inner.getAcceleratorType(request: request, options: options)
  }

  /// Lists runtime versions supported by this API.
  ///
  /// @Snippet(path: "Tpu_ListRuntimeVersions")
  public func listRuntimeVersions(
    request: ListRuntimeVersionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTpuV2.ListRuntimeVersionsResponse {
    try await self.inner.listRuntimeVersions(request: request, options: options)
  }

  /// Gets a runtime version.
  ///
  /// @Snippet(path: "Tpu_GetRuntimeVersion")
  public func getRuntimeVersion(
    request: GetRuntimeVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTpuV2.RuntimeVersion {
    try await self.inner.getRuntimeVersion(request: request, options: options)
  }

  /// Retrieves the guest attributes for the node.
  ///
  /// @Snippet(path: "Tpu_GetGuestAttributes")
  public func getGuestAttributes(
    request: GetGuestAttributesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTpuV2.GetGuestAttributesResponse {
    try await self.inner.getGuestAttributes(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "Tpu_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "Tpu_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Tpu_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Tpu_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Tpu_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Tpu_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `TpuClient`.
  ///
  /// To mock `TpuClient` change your functions to receive
  /// `some TpuProtocol` or `any TpuProtocol`
  /// and pass a mock implementation in your tests.
  public protocol TpuProtocol: Sendable {
    /// See `TpuClient.listNodes`.
    func listNodes(
      request: ListNodesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTpuV2.ListNodesResponse

    /// See `TpuClient.getNode`.
    func getNode(
      request: GetNodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTpuV2.Node

    /// See `TpuClient.createNode`.
    func createNode(
      request: CreateNodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TpuClient.createNode`.
    func createNodePollingUntilDone(
      request: CreateNodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> Node

    /// See `TpuClient.deleteNode`.
    func deleteNode(
      request: DeleteNodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TpuClient.deleteNode`.
    func deleteNodePollingUntilDone(
      request: DeleteNodeRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `TpuClient.stopNode`.
    func stopNode(
      request: StopNodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TpuClient.stopNode`.
    func stopNodePollingUntilDone(
      request: StopNodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> Node

    /// See `TpuClient.startNode`.
    func startNode(
      request: StartNodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TpuClient.startNode`.
    func startNodePollingUntilDone(
      request: StartNodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> Node

    /// See `TpuClient.updateNode`.
    func updateNode(
      request: UpdateNodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TpuClient.updateNode`.
    func updateNodePollingUntilDone(
      request: UpdateNodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> Node

    /// See `TpuClient.listQueuedResources`.
    func listQueuedResources(
      request: ListQueuedResourcesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTpuV2.ListQueuedResourcesResponse

    /// See `TpuClient.getQueuedResource`.
    func getQueuedResource(
      request: GetQueuedResourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTpuV2.QueuedResource

    /// See `TpuClient.createQueuedResource`.
    func createQueuedResource(
      request: CreateQueuedResourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TpuClient.createQueuedResource`.
    func createQueuedResourcePollingUntilDone(
      request: CreateQueuedResourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> QueuedResource

    /// See `TpuClient.deleteQueuedResource`.
    func deleteQueuedResource(
      request: DeleteQueuedResourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TpuClient.deleteQueuedResource`.
    func deleteQueuedResourcePollingUntilDone(
      request: DeleteQueuedResourceRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `TpuClient.resetQueuedResource`.
    func resetQueuedResource(
      request: ResetQueuedResourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TpuClient.resetQueuedResource`.
    func resetQueuedResourcePollingUntilDone(
      request: ResetQueuedResourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> QueuedResource

    /// See `TpuClient.generateServiceIdentity`.
    func generateServiceIdentity(
      request: GenerateServiceIdentityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTpuV2.GenerateServiceIdentityResponse

    /// See `TpuClient.listAcceleratorTypes`.
    func listAcceleratorTypes(
      request: ListAcceleratorTypesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTpuV2.ListAcceleratorTypesResponse

    /// See `TpuClient.getAcceleratorType`.
    func getAcceleratorType(
      request: GetAcceleratorTypeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTpuV2.AcceleratorType

    /// See `TpuClient.listRuntimeVersions`.
    func listRuntimeVersions(
      request: ListRuntimeVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTpuV2.ListRuntimeVersionsResponse

    /// See `TpuClient.getRuntimeVersion`.
    func getRuntimeVersion(
      request: GetRuntimeVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTpuV2.RuntimeVersion

    /// See `TpuClient.getGuestAttributes`.
    func getGuestAttributes(
      request: GetGuestAttributesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTpuV2.GetGuestAttributesResponse

    /// See `TpuClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `TpuClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `TpuClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `TpuClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `TpuClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.TpuProtocol {
  public func listNodes(request: ListNodesRequest) async throws
    -> GoogleCloudTpuV2.ListNodesResponse
  {
    try await self.listNodes(request: request, options: .init())
  }

  public func listNodes(
    request: ListNodesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTpuV2.ListNodesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listNodesByItems(
    request: ListNodesRequest
  ) -> some AsyncSequence<Node, Swift.Error> & Sendable {
    self.listNodesByItems(request: request, options: .init())
  }

  /// Lists nodes.
  ///
  /// @Snippet(path: "Tpu_ListNodes")
  public func listNodesByItems(
    request: ListNodesRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<Node, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudTpuV2.ListNodesResponse in
      var request = request
      request.pageToken = token
      return try await self.listNodes(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listNodesByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<Node, Swift.Error> & Sendable {
    let request = ListNodesRequest().with {
      $0.parent = parent
    }
    return self.listNodesByItems(request: request)
  }

  public func getNode(request: GetNodeRequest) async throws -> GoogleCloudTpuV2.Node {
    try await self.getNode(request: request, options: .init())
  }

  public func getNode(
    request: GetNodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTpuV2.Node {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getNode(
    name: Swift.String,
  ) async throws -> GoogleCloudTpuV2.Node {
    let request = GetNodeRequest().with {
      $0.name = name
    }
    return try await self.getNode(request: request)
  }

  public func createNode(request: CreateNodeRequest) async throws -> GoogleLongRunning.Operation {
    try await self.createNode(request: request, options: .init())
  }

  public func createNode(
    request: CreateNodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createNodePollingUntilDone(request: CreateNodeRequest) async throws -> Node {
    return try await self.createNodePollingUntilDone(request: request, options: .init())
  }

  public func createNodePollingUntilDone(
    request: CreateNodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> Node {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createNodePollingUntilDone(
    parent: Swift.String,
    node: Node?,
    nodeId: Swift.String,
  ) async throws -> Node {
    let request = CreateNodeRequest().with {
      $0.parent = parent
      $0.node = node
      $0.nodeId = nodeId
    }
    return try await self.createNodePollingUntilDone(request: request)
  }

  public func deleteNode(request: DeleteNodeRequest) async throws -> GoogleLongRunning.Operation {
    try await self.deleteNode(request: request, options: .init())
  }

  public func deleteNode(
    request: DeleteNodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteNodePollingUntilDone(request: DeleteNodeRequest) async throws {
    try await self.deleteNodePollingUntilDone(request: request, options: .init())
  }

  public func deleteNodePollingUntilDone(
    request: DeleteNodeRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteNodePollingUntilDone(
    name: Swift.String,
  ) async throws {
    let request = DeleteNodeRequest().with {
      $0.name = name
    }
    try await self.deleteNodePollingUntilDone(request: request)
  }

  public func stopNode(request: StopNodeRequest) async throws -> GoogleLongRunning.Operation {
    try await self.stopNode(request: request, options: .init())
  }

  public func stopNode(
    request: StopNodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func stopNodePollingUntilDone(request: StopNodeRequest) async throws -> Node {
    return try await self.stopNodePollingUntilDone(request: request, options: .init())
  }

  public func stopNodePollingUntilDone(
    request: StopNodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> Node {
    throw GoogleGax.RequestError.unimplemented
  }

  public func startNode(request: StartNodeRequest) async throws -> GoogleLongRunning.Operation {
    try await self.startNode(request: request, options: .init())
  }

  public func startNode(
    request: StartNodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func startNodePollingUntilDone(request: StartNodeRequest) async throws -> Node {
    return try await self.startNodePollingUntilDone(request: request, options: .init())
  }

  public func startNodePollingUntilDone(
    request: StartNodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> Node {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateNode(request: UpdateNodeRequest) async throws -> GoogleLongRunning.Operation {
    try await self.updateNode(request: request, options: .init())
  }

  public func updateNode(
    request: UpdateNodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateNodePollingUntilDone(request: UpdateNodeRequest) async throws -> Node {
    return try await self.updateNodePollingUntilDone(request: request, options: .init())
  }

  public func updateNodePollingUntilDone(
    request: UpdateNodeRequest, options: GoogleGax.RequestOptions
  ) async throws -> Node {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateNodePollingUntilDone(
    node: Node?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> Node {
    let request = UpdateNodeRequest().with {
      $0.node = node
      $0.updateMask = updateMask
    }
    return try await self.updateNodePollingUntilDone(request: request)
  }

  public func listQueuedResources(request: ListQueuedResourcesRequest) async throws
    -> GoogleCloudTpuV2.ListQueuedResourcesResponse
  {
    try await self.listQueuedResources(request: request, options: .init())
  }

  public func listQueuedResources(
    request: ListQueuedResourcesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTpuV2.ListQueuedResourcesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listQueuedResourcesByItems(
    request: ListQueuedResourcesRequest
  ) -> some AsyncSequence<QueuedResource, Swift.Error> & Sendable {
    self.listQueuedResourcesByItems(request: request, options: .init())
  }

  /// Lists queued resources.
  ///
  /// @Snippet(path: "Tpu_ListQueuedResources")
  public func listQueuedResourcesByItems(
    request: ListQueuedResourcesRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<QueuedResource, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudTpuV2.ListQueuedResourcesResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listQueuedResources(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listQueuedResourcesByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<QueuedResource, Swift.Error> & Sendable {
    let request = ListQueuedResourcesRequest().with {
      $0.parent = parent
    }
    return self.listQueuedResourcesByItems(request: request)
  }

  public func getQueuedResource(request: GetQueuedResourceRequest) async throws
    -> GoogleCloudTpuV2.QueuedResource
  {
    try await self.getQueuedResource(request: request, options: .init())
  }

  public func getQueuedResource(
    request: GetQueuedResourceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTpuV2.QueuedResource {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getQueuedResource(
    name: Swift.String,
  ) async throws -> GoogleCloudTpuV2.QueuedResource {
    let request = GetQueuedResourceRequest().with {
      $0.name = name
    }
    return try await self.getQueuedResource(request: request)
  }

  public func createQueuedResource(request: CreateQueuedResourceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createQueuedResource(request: request, options: .init())
  }

  public func createQueuedResource(
    request: CreateQueuedResourceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createQueuedResourcePollingUntilDone(request: CreateQueuedResourceRequest)
    async throws -> QueuedResource
  {
    return try await self.createQueuedResourcePollingUntilDone(request: request, options: .init())
  }

  public func createQueuedResourcePollingUntilDone(
    request: CreateQueuedResourceRequest, options: GoogleGax.RequestOptions
  ) async throws -> QueuedResource {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createQueuedResourcePollingUntilDone(
    parent: Swift.String,
    queuedResource: QueuedResource?,
    queuedResourceId: Swift.String,
  ) async throws -> QueuedResource {
    let request = CreateQueuedResourceRequest().with {
      $0.parent = parent
      $0.queuedResource = queuedResource
      $0.queuedResourceId = queuedResourceId
    }
    return try await self.createQueuedResourcePollingUntilDone(request: request)
  }

  public func deleteQueuedResource(request: DeleteQueuedResourceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteQueuedResource(request: request, options: .init())
  }

  public func deleteQueuedResource(
    request: DeleteQueuedResourceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteQueuedResourcePollingUntilDone(request: DeleteQueuedResourceRequest)
    async throws
  {
    try await self.deleteQueuedResourcePollingUntilDone(request: request, options: .init())
  }

  public func deleteQueuedResourcePollingUntilDone(
    request: DeleteQueuedResourceRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteQueuedResourcePollingUntilDone(
    name: Swift.String,
  ) async throws {
    let request = DeleteQueuedResourceRequest().with {
      $0.name = name
    }
    try await self.deleteQueuedResourcePollingUntilDone(request: request)
  }

  public func resetQueuedResource(request: ResetQueuedResourceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.resetQueuedResource(request: request, options: .init())
  }

  public func resetQueuedResource(
    request: ResetQueuedResourceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func resetQueuedResourcePollingUntilDone(request: ResetQueuedResourceRequest) async throws
    -> QueuedResource
  {
    return try await self.resetQueuedResourcePollingUntilDone(request: request, options: .init())
  }

  public func resetQueuedResourcePollingUntilDone(
    request: ResetQueuedResourceRequest, options: GoogleGax.RequestOptions
  ) async throws -> QueuedResource {
    throw GoogleGax.RequestError.unimplemented
  }

  public func resetQueuedResourcePollingUntilDone(
    name: Swift.String,
  ) async throws -> QueuedResource {
    let request = ResetQueuedResourceRequest().with {
      $0.name = name
    }
    return try await self.resetQueuedResourcePollingUntilDone(request: request)
  }

  public func generateServiceIdentity(request: GenerateServiceIdentityRequest) async throws
    -> GoogleCloudTpuV2.GenerateServiceIdentityResponse
  {
    try await self.generateServiceIdentity(request: request, options: .init())
  }

  public func generateServiceIdentity(
    request: GenerateServiceIdentityRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTpuV2.GenerateServiceIdentityResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAcceleratorTypes(request: ListAcceleratorTypesRequest) async throws
    -> GoogleCloudTpuV2.ListAcceleratorTypesResponse
  {
    try await self.listAcceleratorTypes(request: request, options: .init())
  }

  public func listAcceleratorTypes(
    request: ListAcceleratorTypesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTpuV2.ListAcceleratorTypesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAcceleratorTypesByItems(
    request: ListAcceleratorTypesRequest
  ) -> some AsyncSequence<AcceleratorType, Swift.Error> & Sendable {
    self.listAcceleratorTypesByItems(request: request, options: .init())
  }

  /// Lists accelerator types supported by this API.
  ///
  /// @Snippet(path: "Tpu_ListAcceleratorTypes")
  public func listAcceleratorTypesByItems(
    request: ListAcceleratorTypesRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<AcceleratorType, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudTpuV2.ListAcceleratorTypesResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listAcceleratorTypes(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listAcceleratorTypesByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<AcceleratorType, Swift.Error> & Sendable {
    let request = ListAcceleratorTypesRequest().with {
      $0.parent = parent
    }
    return self.listAcceleratorTypesByItems(request: request)
  }

  public func getAcceleratorType(request: GetAcceleratorTypeRequest) async throws
    -> GoogleCloudTpuV2.AcceleratorType
  {
    try await self.getAcceleratorType(request: request, options: .init())
  }

  public func getAcceleratorType(
    request: GetAcceleratorTypeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTpuV2.AcceleratorType {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAcceleratorType(
    name: Swift.String,
  ) async throws -> GoogleCloudTpuV2.AcceleratorType {
    let request = GetAcceleratorTypeRequest().with {
      $0.name = name
    }
    return try await self.getAcceleratorType(request: request)
  }

  public func listRuntimeVersions(request: ListRuntimeVersionsRequest) async throws
    -> GoogleCloudTpuV2.ListRuntimeVersionsResponse
  {
    try await self.listRuntimeVersions(request: request, options: .init())
  }

  public func listRuntimeVersions(
    request: ListRuntimeVersionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTpuV2.ListRuntimeVersionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listRuntimeVersionsByItems(
    request: ListRuntimeVersionsRequest
  ) -> some AsyncSequence<RuntimeVersion, Swift.Error> & Sendable {
    self.listRuntimeVersionsByItems(request: request, options: .init())
  }

  /// Lists runtime versions supported by this API.
  ///
  /// @Snippet(path: "Tpu_ListRuntimeVersions")
  public func listRuntimeVersionsByItems(
    request: ListRuntimeVersionsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<RuntimeVersion, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudTpuV2.ListRuntimeVersionsResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listRuntimeVersions(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listRuntimeVersionsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<RuntimeVersion, Swift.Error> & Sendable {
    let request = ListRuntimeVersionsRequest().with {
      $0.parent = parent
    }
    return self.listRuntimeVersionsByItems(request: request)
  }

  public func getRuntimeVersion(request: GetRuntimeVersionRequest) async throws
    -> GoogleCloudTpuV2.RuntimeVersion
  {
    try await self.getRuntimeVersion(request: request, options: .init())
  }

  public func getRuntimeVersion(
    request: GetRuntimeVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTpuV2.RuntimeVersion {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getRuntimeVersion(
    name: Swift.String,
  ) async throws -> GoogleCloudTpuV2.RuntimeVersion {
    let request = GetRuntimeVersionRequest().with {
      $0.name = name
    }
    return try await self.getRuntimeVersion(request: request)
  }

  public func getGuestAttributes(request: GetGuestAttributesRequest) async throws
    -> GoogleCloudTpuV2.GetGuestAttributesResponse
  {
    try await self.getGuestAttributes(request: request, options: .init())
  }

  public func getGuestAttributes(
    request: GetGuestAttributesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTpuV2.GetGuestAttributesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> some AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "Tpu_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Tpu_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
